export const ADMIN_FS_TOKEN = 'ADMIN_FS_TOKEN';
export const ADMIN_FS_ID = 'ADMIN_FS_AC_ID';
export const ADMIN_FS_USER_ID = 'ADMIN_FS_USER_ID';
export const ADMIN_FS_LOGIN_SUCCESS = 'ADMIN_FS_LOGIN_SUCCESS';
export const ADMIN_FS_LOGOUT_SUCCESS = 'ADMIN_FS_LOGOUT_SUCCESS';
export const ADMIN_FS_ACCOUNT = 'ADMIN_FS_ACCOUNT';

export const USER_FS_TOKEN = 'USER_FS_TOKEN';

export const FS_ACCOUNT_TYPE = 'FS_ACCOUNT_TYPE';
export const USER_FS_LOGIN_SUCCESS = 'USER_FS_LOGIN_SUCCESS';
export const USER_FS_LOGOUT_SUCCESS = 'USER_FS_LOGOUT_SUCCESS';
export const API_ERROR = 'API_ERROR';
export const CLEAR_ERROR = 'CLEAR_ERROR';

export const SHOW_DIALOG = 'SHOW_DIALOG';
export const CLOSE_DIALOG = 'CLOSE_DIALOG';
export const SHOW_ALERT_DIALOG = 'SHOW_ALERT_DIALOG';
export const SHOW_CONFIRMATION_DIALOG = 'SHOW_CONFIRMATION_DIALOG';

export const DIALOG_TYPE_ALERT = 'DIALOG_TYPE_ALERT';
export const DIALOG_TYPE_CONFIRMATION = 'DIALOG_TYPE_CONFIRMATION';

export const SESSION_EXPIRED_ERROR_MESSAGE = 'Invalid Session or Session expired.';

//data
export const FETCH_ADMIN_PRODUCT_TYPES = 'FETCH_ADMIN_PRODUCT_TYPES';
export const FETCH_USER_PRODUCT_TYPES='FETCH_USER_PRODUCT_TYPES'


//clear
export const CLEAR_ALL_DATA = 'CLEAR_ALL_DATA';
export const CLEAR_ADMIN_PRODUCT_TYPES = 'CLEAR_ADMIN_PRODUCT_TYPES';
export const CLEAR_USER_PRODUCT_TYPES = 'CLEAR_USER_PRODUCT_TYPES';

//theme
export const SET_THEME_DARK = 'SET_THEME_DARK';
export const SET_THEME_LIGHT = 'SET_THEME_LIGHT';